### ISSUE TITLE
The Repository structure is not as required.

### ISSUE THREAD

**Issue by pushpdeep** [chandni143-d/virtual-lab#1]
Please refer this structure here and correct it ASAP.

the repository structure -
http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates

Documentation on porting of the experiment -
https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
@chandni143-d

**Comment by chandni143-d** [comment]
issue is resolve and repository is correct form

**Comment by chandni143-d** [comment]
issue is resolve and repository is correct form
